### ISSUE TITLE
Why performance is inconsistent with that shown in paper?

### ISSUE THREAD

**Issue by KennyNH** [sqrhussain/structack#2]
It seems that after running Structack, the accuracy doesn't see significant drop. I reproduced the code with parameter "--model gcn --dataset cora". Accuracy of "clean" mode is 0.82+ while accuracy of "structack" mode is no less than 0.81. Is there any problem?

**Comment by sqrhussain** [comment]
Hi,

I just realized that the perturbation rate was set to 0.01 for Structack. I've updated it to 0.05 as mentioned in the paper just now.
Could you check if the problem is solved, and close the issue if that's the case?

Best,
Hussain

**Comment by KennyNH** [comment]
Thanks for your reply, it has been solved.
