### ISSUE TITLE
hungarian algorithm

### ISSUE THREAD

**Issue by KennyNH** [sqrhussain/structack#3]
In node connection procedure, the cost matrix mtx is not square which means dims of rows and cols are not the same. Does it affect the result of matching when using linear_sum_assignment from scipy?

**Comment by KennyNH** [comment]
To be more specific, when n_perturbation > len(nodes) and n_perturbation > len(nodes)/2 as well, is that ok?

**Comment by sqrhussain** [comment]
The cost matrix should be a square (n_perturbation * n_perturbation), which means we should have `n_rows = n_cols = n_perturbation`

**Comment by KennyNH** [comment]
Thanks for your reply, now I get it.
